name: home
description: App for the alexander gherardi smart home

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: ^4.1.3
  connectivity: ^0.4.8+6
  graphql_flutter: ^3.0.1
  multicast_dns: ^0.2.2
  animations: ^1.1.1
  flutter_svg: ^0.18.1
  shared_preferences: ^0.5.10

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf

  uses-material-design: true
  assets:
    - assets/
